# 설정
# ========================================================================================

# 사이트의 URL을 설정하려면 주석을 해제하고 설정하세요 (프로토콜 포함, 예: `https://`)
# 참고: GitHub Pages나 Netlify에 호스팅하는 경우 이 속성을 제공할 필요가 없습니다.
# url:                   https://username.github.io

# 사이트의 "기본 URL"을 설정하려면 주석을 해제하고 설정하세요.
# 사이트가 하위 디렉토리에 있을 때, `/<디렉토리 이름>`으로 설정하세요,
# 앞에 `/`를 추가하되 뒤에 `/`는 추가하지 마세요. 그렇지 않으면 빈 문자열 ''을 사용하세요.
# 참고: GitHub Pages나 Netlify에 호스팅하는 경우 이 속성을 제공할 필요가 없습니다.
# baseurl:               '/hydejack-starter-kit'

# 일반 설정
# ---------------------------------------------------------------------------------------

# 콘텐츠의 언어를 2글자 코드로 설정하세요, 예: en, de.
# 위치를 제공할 수도 있습니다, 예: en-us, de_AT.
lang: ko-KR

# 블로그의 제목입니다. 사이드바와 브라우저 탭에 사용됩니다.
title: H0ri

# 메타 설명 태그에 사용되는 페이지의 짧은 설명 (~150자)입니다.
# 마크다운을 사용할 수 있지만 한 단락을 초과하지 않도록 하세요 (`>`로 강제됨).
description: >
  프론트엔드 개발 & 일본어 공부를 위한 블로그입니다.

# 사이드바를 위한 짧은 설명입니다.
tagline: 호리의 종합 발자취

# 블로그에 대한 키워드 목록
keywords: [frontend, 일본어]

# 사이트의 (정사각형) 로고입니다.
# 제공되는 경우 사이드바 상단에 표시됩니다.
# `jekyll-seo-tag` 플러그인에서도 사용됩니다.
logo: /assets/img/logo.png

# `_data/authors.yml`의 첫 번째 항목과 동일한 저자여야 합니다.
author:
  # `jekyll-feed`에서 사용됨:
  name: Lee Ho
  email:
    bomlang4211@gmail.com
    # # `jekyll-seo-tag`에서 사용됨:
  # twitter:             <username>

# 사이드바에 링크를 추가합니다.
menu:
  - title: lifelog
    url: /lifelog/
  - title: 공부
    url: /study/
    submenu:
      - title: React
        url: /react/
      - title: tailwindCSS
        url: /tailwind/
  - title: 프로젝트
    url: /project/
  - title: 日本語勉強
    url: /japanese/
    submenu:
      - title: 宿題
        url: /homework/
      - title: 文法
        url: /grammar/

# 푸터에 링크를 추가합니다.
# 일반적으로 쿠키 정책이나 개인정보 보호정책 등에 링크를 추가하는 것이 좋습니다.
legal:
  - title: LICENSE
    url: /LICENSE/
  - title: NOTICE
    url: /NOTICE/
  - title: CHANGELOG
    url: /CHANGELOG/

# 이 텍스트는 모든 페이지의 푸터에 `<small>` 태그로 나타납니다.
copyright: © 2023. All rights reserved.

# 고유 링크 형식
permalink: /:categories/:year-:month-:day-:title/

# 페이지네이션 설정 (블로그 레이아웃에서 사용됨)
paginate: 10
paginate_path: /:num/

# 테마
# ---------------------------------------------------------------------------------------

remote_theme: qwtel/hydejack@v8.1.1
# theme: jekyll-theme-hydejack
# remote_theme: hydecorp/hydejack@v9

# 커스터마이징
# ----------------------------------------------------------------------------------------

# 사이트의 사이드바 이미지 및 테마 색상.
accent_image: /assets/img/earth.jpg
accent_color: rgb(79,177,186)

# `theme-color` 메타 태그에 사용됩니다.
# 특정 브라우저에서 브라우저 UI의 배경색을 변경합니다.
# 기본값은 `accent_color`입니다.
theme_color: rgb(25,55,71)

# Google Fonts에서 가져올 글꼴을 인코딩하는 문자열입니다.
# 자세한 내용은 <https://hydejack.com/docs/configuration/>을 참조하세요.
google_fonts: Roboto+Slab:700|Noto+Sans:400,400i,700,700i

# 텍스트 글꼴입니다. 유효한 CSS 글꼴 패밀리 값을 기대합니다.
# 글꼴 굵기를 변경하려면 _sass/variables.scss를 참조하세요.
font: Noto Sans, Helvetica, Arial, sans-serif

# 헤딩에 사용되는 글꼴입니다. 유효한 CSS 글꼴 패밀리 값을 기대합니다.
# 글꼴 굵기를 변경하려면 _sass/variables.scss를 참조하세요.
font_heading: Roboto Slab, Helvetica, Arial, sans-serif

# 코드 블록에 사용되는 글꼴입니다. 유효한 CSS 글꼴 패밀리 값을 기대합니다.
font_code: Fira Code, Menlo, Monaco, Consolas, monospace;

defaults:
  # 다음을 사용하여 주어진 경로 아래의 모든 페이지에 대한 기본 강조 색상과 배경을 제공할 수 있습니다:
  - scope:
      path: hyde/
    values:
      accent_color: rgb(38,139,210)
      theme_color: rgb(32,32,32)
      accent_image:
        background: rgb(32,32,32)
        overlay: false

    # 사이트맵에서 assets에 있는 문서를 포함하지 마세요.
  - scope:
      path: assets/
    values:
      sitemap: false

  - scope:
      path: licenses/
    values:
      layout: plain
      sitemap: false

  # # You can use the following to enable comments on all posts.
  # - scope:
  #     type:            posts
  #   values:
  #     comments:        true

  # `jekyll-seo-tag` will mark collection outputs as `BlogPosting`,
  # but we want them to be `WebPage`s:
  - scope:
      type: projects
    values:
      seo:
        type: WebPage
  - scope:
      type: featured_categories
    values:
      seo:
        type: WebPage
  - scope:
      type: featured_tags
    values:
      seo:
        type: WebPage

kramdown:
  math_engine: mathjax
  math_engine_opts: {}
  footnote_backlink: "&#x21a9;&#xfe0e;"

# 3rd Party Integrations
# ----------------------------------------------------------------------------------------

# Set your Google Analytics id to receive `pageview` events.
# To remove Google Anaylics from your page, remove the line below.
# google_analytics:      UA-XXXXXXXX-X

# Setting a disqus shortname will enable the comment section on
# pages with `comments: true` in the front matter.
# disqus:                <username>

# Setting a tinyletter username will enable the newsletter subscription box.
# PRO version only!
# tinyletter:            <username>

# Hydejack Settings
# ----------------------------------------------------------------------------------------
# These settings are specific to Hydejack.

hydejack:
  # Configure the order of complementary content on blog posts
  post_addons: [about, newsletter, related, random, comments]

  # Configure the order of complementary content on project pages
  project_addons: [about, newsletter, other, comments]

  # Set to `true` if you don't want to show an icon indicating external links
  no_mark_external: false

  # Set to `true` if third party plugins fail to work with dynamically loaded pages
  no_push_state: false

  # Set to `true` if you want to disable the drawer
  no_drawer: false

  # Set to `true` if you don't to use the auto-hiding (JavaScript based) navbar.
  # Note that this will not hide the navbar completely, only replace it with a static one.
  # Use custom css to hide completely, e.g. `#_navbar { display: none }`.
  no_navbar: false

  # Set to true to disable the built-in search functionality.
  # Note that search is disabled during local use to save on build time.
  # Run Jekyll with the `JEKYLL_ENV` environment variable set to `production` to enable.
  no_search: false

  # Set to `true` if you do not want parts of the css inlined in <head/>
  # This will increase site build speed dramatically!
  no_inline_css: false

  # Set to `true` if you don't intend on changing the accent color on a per-page basis.
  # This will increase site build speed!
  no_page_style: false

  # Code blocks and tables "break" the layout by spanning the full available width.
  # Set this to true if you want them to be the same width as other content.
  no_break_layout: true

  # Set to `true` to disable the dynamic Table of Contents on large screens.
  no_toc: false

  # When set to `true`, will not extend the content in the "third column" on large screens.
  # Instead, all content will remains within the center column.
  # Note that this will not affect the Table of Contents, use `no_toc` instead.
  no_third_column: false

  # Set to `true` if you don't like oversized headlines on large screens.
  no_large_headings: false

  # Set to `true` if you do not want to expose your resume and projects
  # in machine-readable formats.
  no_structured_data: false

  # You can set this to `true` if you don't want to set the `theme-color` meta tag,
  # This only affects the meta tag, not the color specified in the app manifest.
  no_theme_color: false

  # Disable the breadcrumbs above the title
  no_breadcrumbs: false

  # Set to `true` when building with the `--lsi` option
  use_lsi: true

  # When using Google Analytics, set to `true` to display a cookie notice banner.
  # When enabled, no user-related data will be stored until the user gives consent.
  cookies_banner: false

  # Set to `true` if you would like to add a "Powered by Hydejack" link in the footer.
  # Note that this setting has no effect when using the free version.
  advertise: false

  # Buyers of the PRO version can opt to hide all dates from the theme.
  # Frequent consumers of online content will know that nothing devalues a post like
  # seeing an old date.
  hide_dates: false

  # TODO
  hide_last_modified: false

  # Note that dark mode only works in the PRO version of Hydejack.
  dark_mode:
    # Set to `true` to always use the dark theme.
    always: false

    # Set to `true` to use the dark theme based on visitors' preference (OS setting).
    dynamic: true

    # Set to `true` to allow visitors to switch between light and dark mode.
    icon: true

  # ⚡️ DANGER ZONE ⚡️
  # ----------------
  # This is an _experimental_ feature.
  # Only use if you know what Service Workers are and how they can impact your site!
  offline:
    enabled: false
    cache_version: 13
    precache_assets:
      - /assets/img/swipe.svg

# Collections
# ----------------------------------------------------------------------------------------

collections:
  featured_categories:
    permalink: /:name/
    output: true

  featured_tags:
    permalink: /tag-:name/
    output: true

  projects:
    permalink: /projects/:path/
    output: true

# File inclusion/exclusion
# ----------------------------------------------------------------------------------------

exclude:
  - .jekyll-cache
  - .sass-cache
  - "*.toml"
  - vendor
  - Gemfile
  - Gemfile.lock
include:
  - .well-known
  - LICENSE.md

# Plugins
# ----------------------------------------------------------------------------------------

plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-include-cache
  - jekyll-last-modified-at

# SEO Tag
# ---------------------------------------------------------------------------------------

# Where you proof that you own this site (used by jekyll-seo-tag)
# google_site_verification: <verification-id>
# -- or --
# webmaster_verifications:
#   google:              <verification-id>
#   bing:                <verification-id>
#   alexa:               <verification-id>
#   yandex:              <verification-id>

# Used for twitter cards
# twitter:
#   username:            <username>

# Used for facebook open graph
# facebook:
#   app_id:              <id>
#   publisher:           <id>
#   admins:              <id>

# Used on index and about sites
# social:
#   name:                <firstname> <lastname>
#   links:
#     - https://twitter.com/<username>
#     - https://github.com/<username>

# Plugin Configs
# ---------------------------------------------------------------------------------------
optional_front_matter:
  remove_originals: true

readme_index:
  remove_originals: true
  with_frontmatter: true

relative_links:
  collections: true

titles_from_headings:
  strip_title: true
  collections: true

compress_html:
  comments: ["<!--", "-->"]
  clippings: all
  endings: all
  ignore:
    envs: [development]

sass:
  style: compressed

# Jekyll Compose Defaults
# ---------------------------------------------------------------------------------------

jekyll_compose:
  default_front_matter:
    drafts:
      layout: post
      description: >
        A short ~160 character description of your post for search engines,
        social media previews, etc.
      image:
        path: /assets/img/sidebar-bg.jpg
    posts:
      layout: post
      description: >
        A short ~160 character description of your post for search engines,
        social media previews, etc.
      image:
        path: /assets/img/sidebar-bg.jpg
    projects:
      layout: project
      description: >
        A short ~160 character description of your post for search engines,
        social media previews, etc.
      image:
        path: /assets/img/sidebar-bg.jpg
      links:
        - title: Project Link
          url: https://example.com
